package doctemplate

import (
	"archive/zip"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// bundleWorkspace zips a prepared workspace into a self-contained kit: the
// template, its dependencies, the brand already applied, the payload, a build
// script and a README.
//
// This is the response when the host has no typesetter, which for this app is
// the common case rather than a failure — it ships as one Go binary and typst
// and tectonic are separate installs. It is also available on demand, because
// handing a designer the exact sources a render used is the only honest way to
// let them work on a template without guessing what the server did.
func bundleWorkspace(workspace string, tpl Template, brand Brand, pdfStandard string) ([]byte, error) {
	entries, err := os.ReadDir(workspace)
	if err != nil {
		return nil, fmt.Errorf("listing the render workspace: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		names = append(names, entry.Name())
	}
	// Deterministic order, so two bundles of the same document are byte-equal
	// and a diff between them means something changed.
	sort.Strings(names)

	var buf bytes.Buffer
	archive := zip.NewWriter(&buf)

	for _, name := range names {
		// #nosec G304 -- name comes from reading the temporary workspace this
		// process created, not from request input.
		content, err := os.ReadFile(filepath.Join(workspace, name))
		if err != nil {
			return nil, fmt.Errorf("reading %s for the bundle: %w", name, err)
		}
		if err := addFile(archive, name, content, false); err != nil {
			return nil, err
		}
	}
	if err := addFile(archive, "build.sh", []byte(bundleBuildScript(tpl, pdfStandard)), true); err != nil {
		return nil, err
	}
	if err := addFile(archive, "README.txt", []byte(bundleReadme(tpl, brand, pdfStandard)), false); err != nil {
		return nil, err
	}
	if err := archive.Close(); err != nil {
		return nil, fmt.Errorf("finalising the bundle: %w", err)
	}
	return buf.Bytes(), nil
}

func addFile(archive *zip.Writer, name string, content []byte, executable bool) error {
	header := &zip.FileHeader{Name: name, Method: zip.Deflate}
	mode := os.FileMode(0o644)
	if executable {
		mode = 0o755
	}
	header.SetMode(mode)
	writer, err := archive.CreateHeader(header)
	if err != nil {
		return fmt.Errorf("adding %s to the bundle: %w", name, err)
	}
	if _, err := writer.Write(content); err != nil {
		return fmt.Errorf("writing %s into the bundle: %w", name, err)
	}
	return nil
}

func bundleBuildScript(tpl Template, pdfStandard string) string {
	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Renders this document. Generated by CareLock Consulting; see README.txt.\n")
	sb.WriteString("set -euo pipefail\ncd \"$(dirname \"$0\")\"\n\n")

	switch tpl.Engine {
	case EngineTypst:
		sb.WriteString("TYPST=\"${TYPST:-typst}\"\n")
		fmt.Fprintf(&sb, "PDF_STD=\"${PDF_STD:-%s}\"\n\n", pdfStandard)
		sb.WriteString("if ! command -v \"$TYPST\" >/dev/null 2>&1; then\n")
		sb.WriteString("  echo \"typst not found. It is a single static binary:\" >&2\n")
		sb.WriteString("  echo \"  https://github.com/typst/typst/releases\" >&2\n")
		sb.WriteString("  exit 1\nfi\n\n")
		fmt.Fprintf(&sb, "\"$TYPST\" compile --root . --input data=%s \\\n", dataName)
		sb.WriteString("  ${PDF_STD:+--pdf-standard \"$PDF_STD\"} \\\n")
		fmt.Fprintf(&sb, "  %s %s\n\n", tpl.Entry, outputName)
		fmt.Fprintf(&sb, "echo \"wrote %s\"\n", outputName)
	case EngineLaTeX:
		sb.WriteString("# XeLaTeX or LuaLaTeX, not pdfLaTeX: carelock.sty uses fontspec.\n")
		sb.WriteString("if command -v tectonic >/dev/null 2>&1; then\n")
		fmt.Fprintf(&sb, "  tectonic -X compile --outdir . %s\n", tpl.Entry)
		sb.WriteString("elif command -v latexmk >/dev/null 2>&1; then\n")
		fmt.Fprintf(&sb, "  latexmk -xelatex -outdir=. %s\n", tpl.Entry)
		sb.WriteString("else\n")
		sb.WriteString("  echo \"Neither tectonic nor latexmk found.\" >&2\n")
		sb.WriteString("  echo \"tectonic is a single binary and downloads what it needs:\" >&2\n")
		sb.WriteString("  echo \"  https://tectonic-typesetting.github.io/\" >&2\n")
		sb.WriteString("  exit 1\nfi\n\n")
		fmt.Fprintf(&sb, "echo \"wrote %s.pdf\"\n", strings.TrimSuffix(tpl.Entry, filepath.Ext(tpl.Entry)))
	}
	return sb.String()
}

func bundleReadme(tpl Template, brand Brand, pdfStandard string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "%s — render sources\n", tpl.Name)
	sb.WriteString(strings.Repeat("=", 60) + "\n\n")
	sb.WriteString("Everything needed to typeset this document, exactly as the server would\n")
	sb.WriteString("have. Unzip, then:\n\n    ./build.sh\n\n")

	switch tpl.Engine {
	case EngineTypst:
		sb.WriteString("Requires typst, a single static binary with no dependencies:\n")
		sb.WriteString("    https://github.com/typst/typst/releases\n\n")
	case EngineLaTeX:
		sb.WriteString("Requires tectonic (a single binary that downloads the TeX packages it\n")
		sb.WriteString("needs on first run) or a TeX distribution with XeLaTeX:\n")
		sb.WriteString("    https://tectonic-typesetting.github.io/\n\n")
	}

	sb.WriteString("Files\n-----\n")
	fmt.Fprintf(&sb, "  %-24s the document, compiled by build.sh\n", tpl.Entry)
	if tpl.Generated {
		sb.WriteString("                           (generated from the payload — regenerate it from\n")
		sb.WriteString("                           the app rather than hand-editing, or your edits are\n")
		sb.WriteString("                           lost on the next render)\n")
	}
	fmt.Fprintf(&sb, "  %-24s the render payload\n", dataName)
	for _, source := range tpl.Sources {
		name := filepath.Base(source)
		if name == filepath.Base(tpl.Entry) {
			continue
		}
		switch name {
		case "brand.typ":
			fmt.Fprintf(&sb, "  %-24s identity, palette and type — the saved brand settings\n", name)
			sb.WriteString("                           are already applied here\n")
		case "lib.typ":
			fmt.Fprintf(&sb, "  %-24s page furniture, cover, tables, callouts\n", name)
		case "carelock.sty":
			fmt.Fprintf(&sb, "  %-24s the LaTeX style; brand overrides are in the\n", name)
			sb.WriteString("                           generated document's preamble, not here\n")
		default:
			fmt.Fprintf(&sb, "  %-24s template dependency\n", name)
		}
	}

	fmt.Fprintf(&sb, "\nBrand\n-----\n  Firm      %s\n  Accent    %s\n  Body      %spt %s\n",
		brand.Firm, brand.Accent, formatPt(brand.BodySize), firstOr(brand.SerifStack, "—"))

	if tpl.Engine == EngineTypst {
		standard := pdfStandard
		if standard == "" {
			standard = "(none — plain PDF 1.7)"
		}
		fmt.Fprintf(&sb, "\nPDF standard\n------------\n  %s\n", standard)
		sb.WriteString("  Override with PDF_STD when building, e.g. PDF_STD=a-2b,ua-1 ./build.sh\n")
	}
	return sb.String()
}

func firstOr(values []string, fallback string) string {
	if len(values) == 0 {
		return fallback
	}
	return values[0]
}
