package doctemplate

import (
	"fmt"
	"strings"
)

// GenerateLaTeX turns a policy payload into a complete .tex document against
// templates/latex/carelock.sty.
//
// The header of templates/latex/policy-document.tex says the LaTeX template
// does not read the policy JSON, because LaTeX has no native data loading and
// the alternatives are error-prone. This is the "generate this file from the
// JSON with a small script" it points at, written in Go so it is covered by the
// same tests and escaping rules as the rest of the app. The committed .tex
// stays as the hand-filled reference the output is checked against.
//
// Every value from the payload goes through latexEscape. A policy body is
// author-supplied prose that routinely contains %, & and $, all of which are
// LaTeX syntax — without escaping the common case is a failed build and the
// uncommon case is a document that executes what it was given.
func GenerateLaTeX(payload PolicyPayload, brand Brand) string {
	var sb strings.Builder

	sb.WriteString("% Generated by internal/doctemplate. Do not edit — regenerate from the\n")
	sb.WriteString("% policy document, or edit templates/latex/policy-document.tex, which is\n")
	sb.WriteString("% the hand-filled reference this generator mirrors.\n%\n")
	sb.WriteString("% Build with XeLaTeX or LuaLaTeX, not pdfLaTeX: the style uses fontspec.\n")
	fmt.Fprintf(&sb, "\\documentclass[%s]{article}\n", brand.LaTeXClassOptions())
	sb.WriteString("\\usepackage{carelock}\n\n")
	sb.WriteString(brand.LaTeXPreamble())
	sb.WriteString("\n")

	title := latexEscape(payload.Title)
	reference := latexEscape(payload.Reference)
	classification := latexEscape(orDash(payload.Classification, "Internal"))

	fmt.Fprintf(&sb, "\\setcldoctitle{%s}\n", title)
	fmt.Fprintf(&sb, "\\setclreference{%s}\n", reference)
	fmt.Fprintf(&sb, "\\setclclassification{%s}\n\n", classification)

	sb.WriteString("\\begin{document}\n\n")
	fmt.Fprintf(&sb, "\\clcoverpage{%s}{%s}{%s}\n\n",
		title, latexEscape(payload.DocTypeLabel()), latexEscape(payload.ClientName))

	writeCoverFields(&sb, payload)

	sb.WriteString("\n\\clearpage\n\\pagestyle{clbody}\n\n")
	writeDocumentControl(&sb, payload)
	writeSummary(&sb, payload)
	writeRevisionHistory(&sb, payload)

	sb.WriteString("\n\\clearpage\n\\renewcommand{\\contentsname}{Contents}\n\\tableofcontents\n\\clearpage\n\n")
	writeBody(&sb, payload)
	writeControlMapping(&sb, payload)

	sb.WriteString("\n\\vspace{1.5em}\n")
	fmt.Fprintf(&sb, "\\clapproval{%s}{%s}{%s}\n\n",
		latexEscape(payload.Approver), latexEscape(payload.OwnerRole), latexEscape(payload.EffectiveDate))
	sb.WriteString("\\end{document}\n")
	return sb.String()
}

// coverColumnSpec is the three-column X spec used for the cover field block.
// Hyphenation is suppressed because these are short field values in narrow
// columns, where a hyphenated break ("Of-ficer") is far more visible than a
// ragged edge — the same reasoning as the reference .tex.
const coverColumnSpec = `>{\raggedright\hyphenpenalty=10000\arraybackslash}X`

func writeCoverFields(sb *strings.Builder, payload PolicyPayload) {
	fmt.Fprintf(sb, "\\begin{tabularx}{\\linewidth}{@{}%s%s%s@{}}\n",
		coverColumnSpec, coverColumnSpec, coverColumnSpec)

	fields := [][2]string{
		{"Reference", payload.Reference},
		{"Document type", payload.DocTypeLabel()},
		{"Version", payload.LatestVersionLabel()},
		{"Document owner", payload.OwnerRole},
		{"Approver", payload.Approver},
		{"Effective date", payload.EffectiveDate},
		{"Review cycle", reviewCycle(payload.ReviewCadenceMonths)},
		{"Next review", payload.NextReviewDate},
		{"Frameworks", strings.Join(payload.Frameworks, ", ")},
	}
	for i, field := range fields {
		fmt.Fprintf(sb, "  \\cllabel{%s}\\newline %s",
			latexEscape(field[0]), latexEscape(orDash(field[1], "—")))
		switch {
		case i == len(fields)-1:
			sb.WriteString(" \\\\\n")
		case i%3 == 2:
			sb.WriteString(" \\\\[11pt]\n")
		default:
			sb.WriteString(" &\n")
		}
	}
	sb.WriteString("\\end{tabularx}\n")
}

func writeDocumentControl(sb *strings.Builder, payload PolicyPayload) {
	sb.WriteString("\\section*{Document Control}\n")
	sb.WriteString("\\addcontentsline{toc}{section}{Document Control}\n\n")
	sb.WriteString("\\begin{clkvtable}\n")
	pairs := [][2]string{
		{"Reference", payload.Reference},
		{"Title", payload.Title},
		{"Document type", payload.DocTypeLabel()},
		{"Classification", orDash(payload.Classification, "Internal")},
		{"Status", titleCase(payload.Status)},
		{"Document owner", payload.OwnerRole},
		{"Approver", payload.Approver},
		{"Client", payload.ClientName},
		{"Frameworks", strings.Join(payload.Frameworks, ", ")},
		{"Effective date", payload.EffectiveDate},
		{"Next review", payload.NextReviewDate},
	}
	for _, pair := range pairs {
		fmt.Fprintf(sb, "  %s & %s \\\\\n", latexEscape(pair[0]), latexEscape(orDash(pair[1], "—")))
	}
	sb.WriteString("\\end{clkvtable}\n")
}

func writeSummary(sb *strings.Builder, payload PolicyPayload) {
	if strings.TrimSpace(payload.Summary) == "" {
		return
	}
	sb.WriteString("\n\\vspace{1em}\n\\begin{clcallout}\n")
	sb.WriteString("  \\cllabel{Summary}\\par\\vspace{0.2em}\n  ")
	sb.WriteString(latexParagraphs(payload.Summary))
	sb.WriteString("\n\\end{clcallout}\n")
}

func writeRevisionHistory(sb *strings.Builder, payload PolicyPayload) {
	if len(payload.Versions) == 0 {
		return
	}
	// A clause 7.5 requirement, not a nicety: an auditor asks what changed
	// between versions and who approved it.
	sb.WriteString("\n\\vspace{1.2em}\n\\section*{Revision History}\n")
	sb.WriteString("\\addcontentsline{toc}{section}{Revision History}\n\n")
	sb.WriteString("\\rowcolors{2}{}{clTableZebra}\n")
	sb.WriteString("\\begin{tabularx}{\\linewidth}{@{}>{\\sffamily\\small}l>{\\sffamily\\small}l>{\\small}lX@{}}\n")
	sb.WriteString("  \\toprule\n")
	sb.WriteString("  \\sffamily\\bfseries\\small Version & \\sffamily\\bfseries\\small Approved &\n")
	sb.WriteString("  \\sffamily\\bfseries\\small Approved by & \\sffamily\\bfseries\\small Change summary \\\\\n")
	sb.WriteString("  \\midrule\n")
	for _, version := range payload.Versions {
		fmt.Fprintf(sb, "  %s & %s & %s & %s \\\\\n",
			latexEscape(orDash(version.VersionLabel, "—")),
			latexEscape(orDash(version.ApprovedAt, "—")),
			latexEscape(orDash(version.ApprovedBy, "—")),
			latexEscape(orDash(version.ChangeSummary, "—")))
	}
	sb.WriteString("  \\bottomrule\n\\end{tabularx}\n")
}

func writeBody(sb *strings.Builder, payload PolicyPayload) {
	for _, section := range payload.Sections {
		fmt.Fprintf(sb, "\\section{%s}\n", latexEscape(section.Heading))
		body := latexBlocks(section.Body)
		if body != "" {
			sb.WriteString(body)
			sb.WriteString("\n")
		}
		if note := satisfiesNote(section.Controls); note != "" {
			// Rendered as a muted sans aside rather than a numbered note: it is
			// a traceability mark for an assessor, not part of the normative
			// text, and it must not read as a policy statement.
			fmt.Fprintf(sb, "\\par\\vspace{0.2em}\\noindent{\\sffamily\\footnotesize\\color{clMuted}%s}\\par\n",
				latexEscape(note))
		}
		sb.WriteString("\n")
	}
}

func writeControlMapping(sb *strings.Builder, payload PolicyPayload) {
	if len(payload.Controls) == 0 {
		return
	}
	sb.WriteString("\\clearpage\n\\section{Control Mapping}\n")
	sb.WriteString("This document is mapped to the following catalog controls. Coverage is stated\n")
	sb.WriteString("per control: \\emph{full} means this document satisfies the control on its own,\n")
	sb.WriteString("\\emph{partial} means further documents are required, and \\emph{supporting}\n")
	sb.WriteString("means the text contributes context without satisfying the control.\n\n")
	sb.WriteString("\\vspace{0.6em}\n\\rowcolors{2}{}{clTableZebra}\n")
	sb.WriteString("\\begin{tabularx}{\\linewidth}{@{}>{\\ttfamily\\small}lX>{\\small}l>{\\small}l@{}}\n")
	sb.WriteString("  \\toprule\n")
	sb.WriteString("  \\sffamily\\bfseries\\small Control & \\sffamily\\bfseries\\small Name &\n")
	sb.WriteString("  \\sffamily\\bfseries\\small Coverage & \\sffamily\\bfseries\\small Section \\\\\n")
	sb.WriteString("  \\midrule\n")
	for _, control := range payload.Controls {
		fmt.Fprintf(sb, "  %s & %s & %s & %s \\\\\n",
			latexEscape(orDash(control.ControlID, "—")),
			latexEscape(orDash(control.ControlName, "—")),
			latexEscape(titleCase(orDash(control.Coverage, "—"))),
			latexEscape(orDash(control.SectionHeading, "—")))
	}
	sb.WriteString("  \\bottomrule\n\\end{tabularx}\n")
}

// satisfiesNote builds the inline traceability line, matching what
// templates/typst/policy-document.typ writes under each section.
func satisfiesNote(claims []PolicyClaim) string {
	if len(claims) == 0 {
		return ""
	}
	parts := make([]string, 0, len(claims))
	for _, claim := range claims {
		if claim.Coverage == "" || claim.Coverage == "full" {
			parts = append(parts, claim.ControlID)
			continue
		}
		parts = append(parts, claim.ControlID+" ("+claim.Coverage+")")
	}
	return "Satisfies: " + strings.Join(parts, "; ")
}

func reviewCycle(months int) string {
	if months <= 0 {
		return ""
	}
	if months == 1 {
		return "1 month"
	}
	return fmt.Sprintf("%d months", months)
}

func orDash(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

// ---- Escaping and block structure ----

// latexReplacer escapes the characters LaTeX treats as syntax. Backslash is
// handled first by the replacer's single left-to-right pass, so the
// replacements it introduces are not themselves re-escaped.
var latexReplacer = strings.NewReplacer(
	`\`, `\textbackslash{}`,
	`{`, `\{`,
	`}`, `\}`,
	`&`, `\&`,
	`%`, `\%`,
	`$`, `\$`,
	`#`, `\#`,
	`_`, `\_`,
	`~`, `\textasciitilde{}`,
	`^`, `\textasciicircum{}`,
)

// latexEscape makes an arbitrary string safe to place in LaTeX body text.
func latexEscape(s string) string {
	return latexReplacer.Replace(s)
}

// latexParagraphs escapes a run of prose and turns single newlines into spaces,
// for values that go inside a table cell or a box where a hard break would
// break the layout.
func latexParagraphs(s string) string {
	return latexEscape(strings.Join(strings.Fields(s), " "))
}

// latexBlocks renders a section body: blank-line-separated paragraphs, with
// runs of "- " or "1. " lines turned into lists.
//
// This goes one step further than the Typst template, which passes the body
// string through as content and so shows a bullet list as literal "- " lines.
// The difference is deliberate and worth knowing about: LaTeX needs the escape
// pass regardless, and recognising a list while already walking the text is a
// few lines that visibly improve the deliverable. Bringing Typst up to the same
// level means parsing markdown there, and the obvious way to do it — eval() on
// author-supplied text — hands the typesetter arbitrary code.
func latexBlocks(body string) string {
	body = strings.ReplaceAll(body, "\r\n", "\n")
	blocks := strings.Split(body, "\n\n")
	rendered := make([]string, 0, len(blocks))
	for _, block := range blocks {
		block = strings.Trim(block, "\n")
		if strings.TrimSpace(block) == "" {
			continue
		}
		lines := strings.Split(block, "\n")
		if items, ordered, ok := listItems(lines); ok {
			environment := "itemize"
			if ordered {
				environment = "enumerate"
			}
			var sb strings.Builder
			fmt.Fprintf(&sb, "\\begin{%s}\n", environment)
			for _, item := range items {
				fmt.Fprintf(&sb, "  \\item %s\n", latexParagraphs(item))
			}
			fmt.Fprintf(&sb, "\\end{%s}", environment)
			rendered = append(rendered, sb.String())
			continue
		}
		rendered = append(rendered, latexParagraphs(block))
	}
	return strings.Join(rendered, "\n\n")
}

// listItems recognises a block in which every line is a list item, and reports
// whether the list is ordered. All-or-nothing on purpose: a paragraph that
// happens to contain one line starting with a dash is prose, and converting it
// would silently restructure an author's text.
func listItems(lines []string) (items []string, ordered bool, ok bool) {
	items = make([]string, 0, len(lines))
	sawOrdered, sawUnordered := false, false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "- "), strings.HasPrefix(trimmed, "* "):
			sawUnordered = true
			items = append(items, strings.TrimSpace(trimmed[2:]))
		default:
			text, isOrdered := orderedItem(trimmed)
			if !isOrdered {
				return nil, false, false
			}
			sawOrdered = true
			items = append(items, text)
		}
	}
	// A block mixing the two markers is ambiguous, so it stays prose.
	if len(items) == 0 || (sawOrdered && sawUnordered) {
		return nil, false, false
	}
	return items, sawOrdered, true
}

// orderedItem matches "1. text" / "12) text" and returns the text.
func orderedItem(line string) (string, bool) {
	digits := 0
	for digits < len(line) && line[digits] >= '0' && line[digits] <= '9' {
		digits++
	}
	if digits == 0 || digits > 3 || len(line) < digits+2 {
		return "", false
	}
	if line[digits] != '.' && line[digits] != ')' {
		return "", false
	}
	if line[digits+1] != ' ' {
		return "", false
	}
	return strings.TrimSpace(line[digits+2:]), true
}
