// Builds the Policy Studio bundle into internal/policystudio/assets:
//
//   policy-studio.<hash>.js   ES2020 minified IIFE (window.GRCPolicyStudio)
//   policy-studio.<hash>.css
//   manifest.json             every file with its SHA-256 and size, and every
//                             bundled package with its version and licence
//
// and THIRD_PARTY_NOTICES.md at the repository root. It fails on a bundled
// package whose licence is not on the allowlist, and on a bundle over budget.
// Run through scripts/build-policy-studio.sh, which pins the toolchain.
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import * as esbuild from 'esbuild'

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.resolve(here, '..', '..')
const out = path.join(repo, 'internal', 'policystudio', 'assets')

const ALLOWED = new Set(['MIT', 'BSD-2-Clause', 'BSD-3-Clause', 'Apache-2.0', 'ISC', 'MPL-2.0', '0BSD'])
const JS_BUDGET = 800 * 1024

const result = await esbuild.build({
  entryPoints: { 'policy-studio': path.join(here, 'src', 'studio.js') },
  bundle: true,
  format: 'iife',
  target: 'es2020',
  minify: true,
  legalComments: 'none',
  sourcemap: false,
  charset: 'utf8',
  write: false,
  metafile: true,
  outdir: 'out',
  loader: { '.css': 'css' },
  logLevel: 'warning',
})

const css = await esbuild.build({
  entryPoints: [path.join(here, 'src', 'studio.css')],
  bundle: true,
  minify: true,
  write: false,
  outfile: 'out/policy-studio.css',
  logLevel: 'warning',
})

const hash = (buf) => crypto.createHash('sha256').update(buf).digest('hex')
const js = Buffer.from(result.outputFiles.find((f) => f.path.endsWith('.js')).contents)
const cssBuf = Buffer.from(css.outputFiles[0].contents)
if (js.length > JS_BUDGET) {
  console.error('bundle is ' + js.length + ' bytes, over the ' + JS_BUDGET + '-byte budget')
  process.exit(1)
}

// Every package that contributed code, with its licence.
const packages = new Map()
for (const input of Object.keys(result.metafile.inputs)) {
  const i = input.lastIndexOf('node_modules/')
  if (i < 0) continue
  const parts = input.slice(i + 'node_modules/'.length).split('/')
  const name = parts[0].startsWith('@') ? parts[0] + '/' + parts[1] : parts[0]
  if (packages.has(name)) continue
  const dir = path.join(here, 'node_modules', name)
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'))
  const license = typeof pkg.license === 'string' ? pkg.license : ''
  if (!ALLOWED.has(license)) {
    console.error('refusing to bundle ' + name + '@' + pkg.version + ': licence "' + license + '" is not on the allowlist')
    process.exit(1)
  }
  const licenseFile = fs.readdirSync(dir).find((f) => /^licen[cs]e/i.test(f))
  packages.set(name, { name, version: pkg.version, license, text: licenseFile ? fs.readFileSync(path.join(dir, licenseFile), 'utf8').trim() : '' })
}

const jsName = 'policy-studio.' + hash(js).slice(0, 12) + '.js'
const cssName = 'policy-studio.' + hash(cssBuf).slice(0, 12) + '.css'
fs.mkdirSync(out, { recursive: true })
for (const f of fs.readdirSync(out)) {
  if (/^policy-studio\..*\.(js|css)$/.test(f)) fs.rmSync(path.join(out, f))
}
fs.writeFileSync(path.join(out, jsName), js)
fs.writeFileSync(path.join(out, cssName), cssBuf)

const sorted = [...packages.values()].sort((a, b) => a.name.localeCompare(b.name))
const manifest = {
  entry: { js: jsName, css: cssName },
  files: [
    { file: jsName, sha256: hash(js), bytes: js.length },
    { file: cssName, sha256: hash(cssBuf), bytes: cssBuf.length },
  ],
  packages: sorted.map(({ name, version, license }) => ({ name, version, license })),
}
fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n')

let notices = '# Third-party notices\n\nThe Policy Studio editor bundle (`internal/policystudio/assets`) includes the\nfollowing packages. Generated by `web/policy-studio/build.mjs`; do not edit.\n'
for (const p of sorted) notices += '\n## ' + p.name + ' ' + p.version + ' (' + p.license + ')\n\n```\n' + (p.text || 'No licence file shipped; licence: ' + p.license) + '\n```\n'
fs.writeFileSync(path.join(repo, 'THIRD_PARTY_NOTICES.md'), notices)

console.log(jsName + ' ' + js.length + ' bytes, ' + cssName + ' ' + cssBuf.length + ' bytes, ' + sorted.length + ' packages')
